// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmHAlpQp4EGXPZkOPjh6g3pJTEwpQ5wkY',
    appId: '1:816096115168:web:cf89e35418280e9bdb5385',
    messagingSenderId: '816096115168',
    projectId: 'learningapp-45eb4',
    authDomain: 'learningapp-45eb4.firebaseapp.com',
    storageBucket: 'learningapp-45eb4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDup2hMQ4r4odAqKXYuskQV9LtTKIXFANk',
    appId: '1:816096115168:android:70aa952e3a0426a9db5385',
    messagingSenderId: '816096115168',
    projectId: 'learningapp-45eb4',
    storageBucket: 'learningapp-45eb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTG8jsEzuwubFn26y_chx_PgdUGtz3SYs',
    appId: '1:816096115168:ios:c313c9f6c1cd79e3db5385',
    messagingSenderId: '816096115168',
    projectId: 'learningapp-45eb4',
    storageBucket: 'learningapp-45eb4.appspot.com',
    iosClientId: '816096115168-25a1i6ijnbulk4d1dv756smv7orlbihu.apps.googleusercontent.com',
    iosBundleId: 'com.example.samplesite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTG8jsEzuwubFn26y_chx_PgdUGtz3SYs',
    appId: '1:816096115168:ios:c313c9f6c1cd79e3db5385',
    messagingSenderId: '816096115168',
    projectId: 'learningapp-45eb4',
    storageBucket: 'learningapp-45eb4.appspot.com',
    iosClientId: '816096115168-25a1i6ijnbulk4d1dv756smv7orlbihu.apps.googleusercontent.com',
    iosBundleId: 'com.example.samplesite',
  );
}
